export const GET_PAGU_MP = "GET_PAGU_MP";
export const GET_PAGU_MP_PENDING = "GET_PAGU_MP_PENDING";
export const GET_PAGU_MP_FULFILLED = "GET_PAGU_MP_FULFILLED";
export const GET_PAGU_MP_REJECTED = "GET_PAGU_MP_REJECTED";

export const GET_ANGGARAN_REALISASI = "GET_ANGGARAN_REALISASI";
export const GET_ANGGARAN_REALISASI_PENDING = "GET_ANGGARAN_REALISASI_PENDING";
export const GET_ANGGARAN_REALISASI_FULFILLED =
  "GET_ANGGARAN_REALISASI_FULFILLED";
export const GET_ANGGARAN_REALISASI_REJECTED =
  "GET_ANGGARAN_REALISASI_REJECTED";

//global
export const GET_SATKER = "GET_SATKER";
export const GET_SATKER_PENDING = "GET_SATKER_PENDING";
export const GET_SATKER_FULFILLED = "GET_SATKER_FULFILLED";
export const GET_SATKER_REJECTED = "GET_SATKER_REJECTED";

export const GET_KANTOR = "GET_KANTOR";
export const GET_KANTOR_PENDING = "GET_KANTOR_PENDING";
export const GET_KANTOR_FULFILLED = "GET_KANTOR_FULFILLED";
export const GET_KANTOR_REJECTED = "GET_KANTOR_REJECTED";

export const GET_KANWIL = "GET_KANWIL";
export const GET_KANWIL_PENDING = "GET_KANWIL_PENDING";
export const GET_KANWIL_FULFILLED = "GET_KANWIL_FULFILLED";
export const GET_KANWIL_REJECTED = "GET_KANWIL_REJECTED";

//global
export const GET_TAHUN = "GET_TAHUN";
export const GET_TAHUN_PENDING = "GET_TAHUN_PENDING";
export const GET_TAHUN_FULFILLED = "GET_TAHUN_FULFILLED";
export const GET_TAHUN_REJECTED = "GET_TAHUN_REJECTED";

export const GET_KANTAH = "GET_KANTAH";
export const GET_KANTAH_PENDING = "GET_KANTAH_PENDING";
export const GET_KANTAH_FULFILLED = "GET_KANTAH_FULFILLED";
export const GET_KANTAH_REJECTED = "GET_KANTAH_REJECTED";

export const GET_KANWIL_MITRA = "GET_KANWIL_MITRA";
export const GET_KANWIL_MITRA_PENDING = "GET_KANWIL_MITRA_PENDING";
export const GET_KANWIL_MITRA_FULFILLED = "GET_KANWIL_MITRA_FULFILLED";
export const GET_KANWIL_MITRA_REJECTED = "GET_KANWIL_MITRA_REJECTED";

//PNBP
export const GET_KANTOR_REALISASI_PENGGUNAAN =
  "GET_KANTOR_REALISASI_PENGGUNAAN";
export const GET_KANTOR_REALISASI_PENGGUNAAN_PENDING =
  "GET_KANTOR_REALISASI_PENGGUNAAN_PENDING";
export const GET_KANTOR_REALISASI_PENGGUNAAN_FULFILLED =
  "GET_KANTOR_REALISASI_PENGGUNAAN_FULFILLED";
export const GET_KANTOR_REALISASI_PENGGUNAAN_REJECTED =
  "GET_KANTOR_REALISASI_PENGGUNAAN_REJECTED";

export const GET_PENGEMBALIAN_PNBP_FILTER = "GET_PENGEMBALIAN_PNBP_FILTER";
export const GET_PENGEMBALIAN_PNBP_FILTER_PENDING =
  "GET_PENGEMBALIAN_PNBP_FILTER_PENDING";
export const GET_PENGEMBALIAN_PNBP_FILTER_FULFILLED =
  "GET_PENGEMBALIAN_PNBP_FILTER_FULFILLED";
export const GET_PENGEMBALIAN_PNBP_FILTER_REJECTED =
  "GET_PENGEMBALIAN_PNBP_FILTER_REJECTED";

export const GET_BERKAS_PNBP_WILAYAH_FILTER = "GET_BERKAS_PNBP_WILAYAH_FILTER";
export const GET_BERKAS_PNBP_WILAYAH_FILTER_PENDING =
  "GET_BERKAS_PNBP_WILAYAH_FILTER_PENDING";
export const GET_BERKAS_PNBP_WILAYAH_FILTER_FULFILLED =
  "GET_BERKAS_PNBP_WILAYAH_FILTER_FULFILLED";
export const GET_BERKAS_PNBP_WILAYAH_FILTER_REJECTED =
  "GET_BERKAS_PNBP_WILAYAH_FILTER_REJECTED";

export const GET_BERKAS_PNBP_KANTOR_FILTER = "GET_BERKAS_PNBP_KANTOR_FILTER";
export const GET_BERKAS_PNBP_KANTOR_FILTER_PENDING =
  "GET_BERKAS_PNBP_KANTOR_FILTER_PENDING";
export const GET_BERKAS_PNBP_KANTOR_FILTER_FULFILLED =
  "GET_BERKAS_PNBP_KANTOR_FILTER_FULFILLED";
export const GET_BERKAS_PNBP_KANTOR_FILTER_REJECTED =
  "GET_BERKAS_PNBP_KANTOR_FILTER_REJECTED";

export const GET_PERSENTASE_PNBP_BELANJA_FILTER =
  "GET_PERSENTASE_PNBP_BELANJA_FILTER";
export const GET_PERSENTASE_PNBP_BELANJA_FILTER_PENDING =
  "GET_PERSENTASE_PNBP_BELANJA_FILTER_PENDING";
export const GET_PERSENTASE_PNBP_BELANJA_FILTER_FULFILLED =
  "GET_PERSENTASE_PNBP_BELANJA_FILTER_FULFILLED";
export const GET_PERSENTASE_PNBP_BELANJA_FILTER_REJECTED =
  "GET_PERSENTASE_PNBP_BELANJA_FILTER_REJECTED";

export const GET_PNBP_KINERJA_BERKAS_FILTER = "GET_PNBP_KINERJA_BERKAS_FILTER";
export const GET_PNBP_KINERJA_BERKAS_FILTER_PENDING =
  "GET_PNBP_KINERJA_BERKAS_FILTER_PENDING";
export const GET_PNBP_KINERJA_BERKAS_FILTER_FULFILLED =
  "GET_PNBP_KINERJA_BERKAS_FILTER_FULFILLED";
export const GET_PNBP_KINERJA_BERKAS_FILTER_REJECTED =
  "GET_PNBP_KINERJA_BERKAS_FILTER_REJECTED";

//bphtb
export const GET_BPHTB_BERKAS_FILTER = "GET_BPHTB_BERKAS_FILTER";
export const GET_BPHTB_BERKAS_FILTER_PENDING =
  "GET_BPHTB_BERKAS_FILTER_PENDING";
export const GET_BPHTB_BERKAS_FILTER_FULFILLED =
  "GET_BPHTB_BERKAS_FILTER_FULFILLED";
export const GET_BPHTB_BERKAS_FILTER_REJECTED =
  "GET_BPHTB_BERKAS_FILTER_REJECTED";

//kepegawaian
export const GET_TAHUN_MUTASI = "GET_TAHUN_MUTASI";
export const GET_TAHUN_MUTASI_PENDING = "GET_TAHUN_MUTASI_PENDING";
export const GET_TAHUN_MUTASI_FULFILLED = "GET_TAHUN_MUTASI_FULFILLED";
export const GET_TAHUN_MUTASI_REJECTED = "GET_TAHUN_MUTASI_REJECTED";

// ************ SERTIFIKASI  ************
export const GET_KANWIL_SERTIFIKASI = "GET_KANWIL_SERTIFIKASI";
export const GET_KANWIL_SERTIFIKASI_PENDING = "GET_KANWIL_SERTIFIKASI_PENDING";
export const GET_KANWIL_SERTIFIKASI_FULFILLED =
  "GET_KANWIL_SERTIFIKASI_FULFILLED";
export const GET_KANWIL_SERTIFIKASI_REJECTED =
  "GET_KANWIL_SERTIFIKASI_REJECTED";

export const GET_TIPE_HAK_SERTIFIKASI = "GET_TIPE_HAK_SERTIFIKASI";
export const GET_TIPE_HAK_SERTIFIKASI_PENDING =
  "GET_TIPE_HAK_SERTIFIKASI_PENDING";
export const GET_TIPE_HAK_SERTIFIKASI_FULFILLED =
  "GET_TIPE_HAK_SERTIFIKASI_FULFILLED";
export const GET_TIPE_HAK_SERTIFIKASI_REJECTED =
  "GET_TIPE_HAK_SERTIFIKASI_REJECTED";

export const GET_NAMA_PROFILE = "GET_NAMA_PROFILE";
export const GET_NAMA_PROFILE_PENDING = "GET_NAMA_PROFILE_PENDING";
export const GET_NAMA_PROFILE_FULFILLED = "GET_NAMA_PROFILE_FULFILLED";
export const GET_NAMA_PROFILE_REJECTED = "GET_NAMA_PROFILE_REJECTED";

// ************ END SERTIFIKASI  ************
