export const GET_PAGU_MP = "GET_PAGU_MP";
export const GET_PAGU_MP_PENDING = "GET_PAGU_MP_PENDING";
export const GET_PAGU_MP_FULFILLED = "GET_PAGU_MP_FULFILLED";
export const GET_PAGU_MP_REJECTED = "GET_PAGU_MP_REJECTED";

export const GET_ANGGARAN_REALISASI = "GET_ANGGARAN_REALISASI";
export const GET_ANGGARAN_REALISASI_PENDING = "GET_ANGGARAN_REALISASI_PENDING";
export const GET_ANGGARAN_REALISASI_FULFILLED =
  "GET_ANGGARAN_REALISASI_FULFILLED";
export const GET_ANGGARAN_REALISASI_REJECTED =
  "GET_ANGGARAN_REALISASI_REJECTED";
