export const BASE_URL = {
  // domain: "http://10.20.57.234:3000",
  domain: "https://sie.atrbpn.go.id/SIE_FE",
  path: {
    realisasi_anggaran: "sie-pnbp-realisasi-anggaran",
    pagu_mp: "sie-pnbp-pagu-mp",
    pnbp_pagu_mp_ops_non: "sie-pnbp-pagu-mp-ops-non",
    pengembalian_pnbp: "sie-pengembalian-pnbp",
    peringkat_realisasi: "sie-peringkat-realisasi",
    alokasi_anggaran: "sie-pnbp-alokasi-anggaran",
    pnbp_berkas_peringkat_wilayah: "sie-pnbp-berkas-peringkat-wilayah",
    pnbp_berkas_peringkat: "sie-pnbp-berkas-peringkat",
    pnbp_berkas_wilayah: "sie-pnbp-berkas-wilayah",
    kinerja_berkas_pnbp: "sie-pnbp-kinerja-berkas",
    persentase_realisasi_belanja: "sie-pnbp-persentase-realisasi-belanja",
    realisasi_penerimaan: "sie-pnbp-realisasi-penerimaan",
    realisasi_penggunaan: "sie-pnbp-realisasi-penggunaan",
    realisasi_target_penerimaan: "sie-pnbp-realisasi-target-penerimaan",
    psn_ptls_5peringkat: "sie-psn-ptsl-5peringkat",
    KL_LU_Layanan_Jumlah_Perjenis: "sie-layanan-jumlah-perjenis",
    psn_rdtr: "sie-psn-rdtr",
    bphtb_jumlah_berkas: "bphtb-jumlah-berkas",
    bphtb_daerah_terintegrasi: "bphtb-jumlah-terintegrasi",
    kepegawaian_bpn_gol: "kepegawaian-atr-bpn-golongan",
    kepegawaian_bpn_jabatan: "kepegawaian-atr-bpn-jabatan",
    kepegawaian_bpn_jk: "kepegawaian-atr-bpn-JK",
    kepegawaian_bpn_mutasi: "kepegawaian-atr-bpn-mutasi",
    kepegawaian_bpn_pendidikan: "kepegawaian-atr-bpn-pendidikan",
    kepegawaian_bpn_usia: "kepegawaian-atr-bpn-usia",
    kepegawaian_organisasi: "kepegawaian-organisasi",
    sie_layanan_jumlah_perjenis: "sie-layanan-jumlah-perjenis",
    sie_layanan_kebutuhan_kantor_pertanahan:
      "sie-layanan-kebutuhan-kantor-pertanahan",
    sie_psn_rdtr: "sie-psn-rdtr",
    sie_psn_ptsl_5_peringkat: "sie-psn-ptsl-5-peringkat",
    realisasi_kegiatan: "sie-ptsl-realisasi-perkegiatan",
    statistik_kemitraan: "sie-statistik-kemitraan",
    pengadaan_tanah: "sie-psn-luas-pengadaaan-tanah",
    sie_ht_ditutup_perkantor: "sie-ht-ditutup-perkantor",
    sie_ht_jumlah_kantor_tahun: "sie-ht-jumlah-kantor-tahun",
    terbit_tanpa_periksa: "sie-ht-terbit-tanpa-periksa",
    sie_ht_upload_ppat_ip_sama: "sie-ht-upload-ppat-ip-sama",
    tanah_asset_pemerintah: "sie-sertifikasi-aset-pemerintah",
    refroma_agria: "sie-reforma-agria",
    sie_sertifikasi_tahun: "sie-sertifikasi-tahun",
    sie_sertifikasi_target_realisasi: "sie-sertifikasi-target-realisasi",
    sie_sertifikasi_jangka_waktu_hak: "sie-sertifikasi-jangka-waktu-hak",
    sie_sertifikasi_konsolidasi_kota: "sie-sertifikasi-konsolidasi-kota",
    sie_sertifikasi_luas_jumlah: "sie-sertifikasi-luas-jumlah",
    sie_tunggakan: "sie-tunggakan",
    sie_index_tanah: "sie-index-tanah",
    sie_tunggakan_wilayah: "sie-tunggakan-wilayah",
    sie_psn_nilai_bphtb: "sie-psn-nilai-bphtb",
    sie_psn_nilai_pnbp: "sie-psn-nilai-pnbp",
    sie_psn_nilai_ht: "sie-psn-nilai-ht",
    sie_psn_nilai_jual_beli: "sie-psn-nilai-jual-beli",
    sie_psn_nilai_tanah_per_kantah: "sie-psn-nilai-tanah-perkantah",
    sie_dashboard_pegawai: "sie-dashboard-pegawai",
    sie_statistik_pegawai: "sie-statistik-pegawai",
    sie_statistik_pegawai2: "sie-statistik-pegawai2",
  },
};
