export const BASE_URL = {
  // domain: "http://10.20.57.234:3000",
  domain: "http://localhost:3000",
  path: {
    realisasi_anggaran: "sie-pnbp-realisasi-anggaran",
    pagu_mp: "sie-pnbp-pagu-mp",
    pnbp_pagu_mp_ops_non: "sie-pnbp-pagu-mp-ops-non",
    pengembalian_pnbp: "sie-pengembalian-pnbp",
    peringkat_realisasi: "sie-peringkat-realisasi",
    alokasi_anggaran: "sie-pnbp-alokasi-anggaran",
    pnbp_berkas_peringkat_wilayah: "sie-pnbp-berkas-peringkat-wilayah",
    pnbp_berkas_peringkat: "sie-pnbp-berkas-peringkat",
    pnbp_berkas_wilayah: "sie-pnbp-berkas-wilayah",
    kinerja_berkas_pnbp: "sie-pnbp-kinerja-berkas",
    persentase_realisasi_belanja: "sie-pnbp-persentase-realisasi-belanja",
    realisasi_penerimaan: "sie-pnbp-realisasi-penerimaan",
    realisasi_penggunaan: "sie-pnbp-realisasi-penggunaan",
    realisasi_target_penerimaan: "sie-pnbp-realisasi-target-penerimaan",
    psn_ptls_5peringkat: "sie-psn-ptsl-5peringkat",
    KL_LU_Layanan_Jumlah_Perjenis: "sie-layanan-jumlah-perjenis",
    psn_rdtr: "sie-psn-rdtr",
    bphtb_jumlah_berkas: "bphtb-jumlah-berkas",
    bphtb_daerah_terintegrasi: "bphtb-jumlah-terintegrasi",
    kepegawaian_bpn_gol: "kepegawaian-atr-bpn-golongan",
    kepegawaian_bpn_jabatan: "kepegawaian-atr-bpn-jabatan",
    kepegawaian_bpn_jk: "kepegawaian-atr-bpn-JK",
    kepegawaian_bpn_mutasi: "kepegawaian-atr-bpn-mutasi",
    kepegawaian_bpn_pendidikan: "kepegawaian-atr-bpn-pendidikan",
    kepegawaian_bpn_usia: "kepegawaian-atr-bpn-usia",
    kepegawaian_organisasi: "kepegawaian-organisasi",
    sie_layanan_jumlah_perjenis: "sie-layanan-jumlah-perjenis",
    sie_layanan_kebutuhan_kantor_pertanahan:
      "sie-layanan-kebutuhan-kantor-pertanahan",
    sie_psn_rdtr: "sie-psn-rdtr",
    sie_psn_ptsl_5_peringkat: "sie-psn-ptsl-5-peringkat",
    realisasi_kegiatan: "sie-ptsl-realisasi-perkegiatan",
    statistik_kemitraan: "sie-statistik-kemitraan",
    pengadaan_tanah: "sie-psn-luas-pengadaaan-tanah",
    sie_ht_ditutup_perkantor: "sie-ht-ditutup-perkantor",
    sie_ht_jumlah_kantor_tahun: "sie-ht-jumlah-kantor-tahun",
    terbit_tanpa_periksa: "sie-ht-terbit-tanpa-periksa",
    sie_ht_upload_ppat_ip_sama: "sie-ht-upload-ppat-ip-sama",
  },
};
