export const BASE_URL = {
  // domain: "http://10.20.57.234:3000",
  domain: "http://localhost:3000",
  path: {
    realisasi_anggaran: "sie-pnbp-realisasi-anggaran",
    pagu_mp: "sie-pnbp-pagu-mp",
    pnbp_pagu_mp_ops_non: "sie-pnbp-pagu-mp-ops-non",
    pengembalian_pnbp: "sie-pengembalian-pnbp",
    peringkat_realisasi: "sie-peringkat-realisasi",
    alokasi_anggaran: "sie-pnbp-alokasi-anggaran",
    pnbp_berkas_peringkat_wilayah: "sie-pnbp-berkas-peringkat-wilayah",
    pnbp_berkas_peringkat: "sie-pnbp-berkas-peringkat",
    pnbp_berkas_wilayah: "sie-pnbp-berkas-wilayah",
    kinerja_berkas_pnbp: "sie-pnbp-kinerja-berkas",
    persentase_realisasi_belanja: "sie-pnbp-persentase-realisasi-belanja",
    realisasi_penerimaan: "sie-pnbp-realisasi-penerimaan",
    realisasi_penggunaan: "sie-pnbp-realisasi-penggunaan",
    realisasi_target_penerimaan: "sie-pnbp-realisasi-target-penerimaan",
    psn_ptls_5peringkat: "sie-psn-ptsl-5peringkat",
    KL_LU_Layanan_Jumlah_Perjenis: "sie-layanan-jumlah-perjenis",
    psn_rdtr: "sie-psn-rdtr",
  },
};
